version: "3"

services:
  base_mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: presse-sentiment
    networks:
      - presse_network
    volumes:
      - /home/fred/Formation/Simplon/Exercisses/Projet_Mai2020/Projet_final/database:/data
      - /home/fred/Formation/Simplon/Exercisses/Projet_Mai2020/Projet_final/database/db:/data/db
      - /home/fred/Formation/Simplon/Exercisses/Projet_Mai2020/Projet_final/database/configdb:/data/configdb
      - /home/fred/Formation/Simplon/Exercisses/Projet_Mai2020/Projet_final/database/import.sh:/docker-entrypoint-initdb.d/import.sh

  app_flask:
    build: web_app/.
    volumes:
      - /home/fred/Formation/Simplon/Exercisses/Projet_Mai2020/Projet_final/web_app/app_web:/src/app_web
      - /home/fred/Formation/Simplon/Exercisses/Projet_Mai2020/Projet_final/web_app/pack/:/src/pack/
    networks:
      - presse_network
    ports:
      - 5010:5000

  scrapeur_python:
    build: scraping/.
    volumes:
      - /home/fred/Formation/Simplon/Exercisses/Projet_Mai2020/Projet_final/scraping/scrap.log:/src/scrap.log
      - /home/fred/Formation/Simplon/Exercisses/Projet_Mai2020/Projet_final/scraping/scrapeur.py:/src/scrapeur.py
      - /home/fred/Formation/Simplon/Exercisses/Projet_Mai2020/Projet_final/scraping/pack/:/src/pack/
    networks:
      - presse_network

networks:
  presse_network: