version: "3"

services:
  base_mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: presse-sentiment
    networks:
      - presse_network
    volumes:
      - presse-sentiment-database-db:/data/db
      - presse-sentiment-database-configdb:/data/configdb
      # Pour un affichage correct du temps
      - /etc/localtime:/etc/localtime:ro # TODO Vérifier si cela fonctionne sur d'autres OS qu'Ubuntu
      # Pour copier le fichier .json et le script d'initialisation de la base de données
      # >>>>> Modifiez la ligne 21 :
      # >>>>> Remplacez : "/home/fred/Formation/Simplon/Exercisses/Projet_Mai2020/Projet_final"
      # >>>>> Par le chemin absolu menant au dossier du projet
      - /home/fred/Formation/Simplon/Exercisses/Projet_Mai2020/Projet_final/database/:/docker-entrypoint-initdb.d/:ro
      # <<<<< Modifier la ligne précédente <<<<<

  app_flask:
    build: web_app/.
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - presse_network
    ports:
      - 5010:5000 

  scrapeur_python:
    build: scraping/.
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Pour copier les logs dans un ficher local
      # >>>>> Modifiez la ligne 41 :
      # >>>>> Remplacez : "/home/fred/Formation/Simplon/Exercisses/Projet_Mai2020/Projet_final"
      # >>>>> Par le chemin absolu menant au dossier du projet
      - /home/fred/Formation/Simplon/Exercisses/Projet_Mai2020/Projet_final/scraping/scrap.log:/src/scrap.log
      # <<<<< Modifier la ligne précédente <<<<<

    networks:
      - presse_network

networks:
  presse_network:

volumes:
  presse-sentiment-database-db:
  presse-sentiment-database-configdb: